// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID                   string
	SecretEnc            []byte
	RegistrationTokenEnc []byte
	CreatedAt            int64
	ExpiresAt            int64
	Meta                 []byte
}

type Grant struct {
	ID                   string
	RefreshToken         pgtype.Text
	AuthCode             pgtype.Text
	GrantType            string
	Subject              string
	ClientID             string
	Scopes               pgtype.Text
	Nonce                pgtype.Text
	JwkThumbprint        pgtype.Text
	ClientCertThumbprint pgtype.Text
	AuthDetails          []byte
	Resources            []byte
	Store                []byte
	CreatedAt            int64
	ExpiresAt            int64
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash []byte
	Locale       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
