// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const deleteGrant = `-- name: DeleteGrant :exec
DELETE FROM grants WHERE id = $1
`

func (q *Queries) DeleteGrant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGrant, id)
	return err
}

const deleteGrantByAuthCode = `-- name: DeleteGrantByAuthCode :exec
DELETE FROM grants WHERE auth_code = $1
`

func (q *Queries) DeleteGrantByAuthCode(ctx context.Context, authCode pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteGrantByAuthCode, authCode)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, secret_enc, registration_token_enc, created_at, expires_at, meta
FROM clients
WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.SecretEnc,
		&i.RegistrationTokenEnc,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Meta,
	)
	return i, err
}

const getGrant = `-- name: GetGrant :one
SELECT id, refresh_token, auth_code, grant_type, subject, client_id,
       scopes, nonce, jwk_thumbprint, client_cert_thumbprint,
       auth_details, resources, store, created_at, expires_at
FROM grants
WHERE id = $1
`

func (q *Queries) GetGrant(ctx context.Context, id string) (Grant, error) {
	row := q.db.QueryRow(ctx, getGrant, id)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.AuthCode,
		&i.GrantType,
		&i.Subject,
		&i.ClientID,
		&i.Scopes,
		&i.Nonce,
		&i.JwkThumbprint,
		&i.ClientCertThumbprint,
		&i.AuthDetails,
		&i.Resources,
		&i.Store,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getGrantByRefreshToken = `-- name: GetGrantByRefreshToken :one
SELECT id, refresh_token, auth_code, grant_type, subject, client_id,
       scopes, nonce, jwk_thumbprint, client_cert_thumbprint,
       auth_details, resources, store, created_at, expires_at
FROM grants
WHERE refresh_token = $1
`

func (q *Queries) GetGrantByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (Grant, error) {
	row := q.db.QueryRow(ctx, getGrantByRefreshToken, refreshToken)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.AuthCode,
		&i.GrantType,
		&i.Subject,
		&i.ClientID,
		&i.Scopes,
		&i.Nonce,
		&i.JwkThumbprint,
		&i.ClientCertThumbprint,
		&i.AuthDetails,
		&i.Resources,
		&i.Store,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertClient = `-- name: UpsertClient :exec
INSERT INTO clients (id, secret_enc, registration_token_enc, created_at, expires_at, meta)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    secret_enc             = EXCLUDED.secret_enc,
    registration_token_enc = EXCLUDED.registration_token_enc,
    created_at             = EXCLUDED.created_at,
    expires_at             = EXCLUDED.expires_at,
    meta                   = EXCLUDED.meta
`

type UpsertClientParams struct {
	ID                   string
	SecretEnc            []byte
	RegistrationTokenEnc []byte
	CreatedAt            int64
	ExpiresAt            int64
	Meta                 []byte
}

func (q *Queries) UpsertClient(ctx context.Context, arg UpsertClientParams) error {
	_, err := q.db.Exec(ctx, upsertClient,
		arg.ID,
		arg.SecretEnc,
		arg.RegistrationTokenEnc,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Meta,
	)
	return err
}

const upsertGrant = `-- name: UpsertGrant :exec
INSERT INTO grants (
    id, refresh_token, auth_code, grant_type, subject, client_id,
    scopes, nonce, jwk_thumbprint, client_cert_thumbprint,
    auth_details, resources, store, created_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
ON CONFLICT (id) DO UPDATE SET
    refresh_token          = EXCLUDED.refresh_token,
    auth_code              = EXCLUDED.auth_code,
    grant_type             = EXCLUDED.grant_type,
    subject                = EXCLUDED.subject,
    client_id              = EXCLUDED.client_id,
    scopes                 = EXCLUDED.scopes,
    nonce                  = EXCLUDED.nonce,
    jwk_thumbprint         = EXCLUDED.jwk_thumbprint,
    client_cert_thumbprint = EXCLUDED.client_cert_thumbprint,
    auth_details           = EXCLUDED.auth_details,
    resources              = EXCLUDED.resources,
    store                  = EXCLUDED.store,
    created_at             = EXCLUDED.created_at,
    expires_at             = EXCLUDED.expires_at
`

type UpsertGrantParams struct {
	ID                   string
	RefreshToken         pgtype.Text
	AuthCode             pgtype.Text
	GrantType            string
	Subject              string
	ClientID             string
	Scopes               pgtype.Text
	Nonce                pgtype.Text
	JwkThumbprint        pgtype.Text
	ClientCertThumbprint pgtype.Text
	AuthDetails          []byte
	Resources            []byte
	Store                []byte
	CreatedAt            int64
	ExpiresAt            int64
}

func (q *Queries) UpsertGrant(ctx context.Context, arg UpsertGrantParams) error {
	_, err := q.db.Exec(ctx, upsertGrant,
		arg.ID,
		arg.RefreshToken,
		arg.AuthCode,
		arg.GrantType,
		arg.Subject,
		arg.ClientID,
		arg.Scopes,
		arg.Nonce,
		arg.JwkThumbprint,
		arg.ClientCertThumbprint,
		arg.AuthDetails,
		arg.Resources,
		arg.Store,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
