// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, locale)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	Username     string
	PasswordHash []byte
	Locale       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.Locale)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, locale
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash []byte
	Locale       string
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, locale
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash []byte
	Locale       string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    username      = COALESCE($1, username),
    locale        = COALESCE($2, locale),
    password_hash = COALESCE($3, password_hash),
    updated_at    = now()
WHERE id = $4
`

type UpdateUserParams struct {
	Username     pgtype.Text
	Locale       pgtype.Text
	PasswordHash []byte
	ID           pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.Locale,
		arg.PasswordHash,
		arg.ID,
	)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1) AS exists
`

func (q *Queries) UserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
