// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *InternalErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type CreateUserBadRequest ErrorResponse

func (*CreateUserBadRequest) createUserRes() {}

// Ref: #/components/schemas/CreateUserRequest
type CreateUserRequest struct {
	Username string `json:"username"`
	// Plain text; stored as bcrypt hash, never returned.
	Password string `json:"password"`
	// BCP 47 language tag. Defaults to `en` if omitted.
	Locale OptString `json:"locale"`
}

// GetUsername returns the value of Username.
func (s *CreateUserRequest) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *CreateUserRequest) GetPassword() string {
	return s.Password
}

// GetLocale returns the value of Locale.
func (s *CreateUserRequest) GetLocale() OptString {
	return s.Locale
}

// SetUsername sets the value of Username.
func (s *CreateUserRequest) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *CreateUserRequest) SetPassword(val string) {
	s.Password = val
}

// SetLocale sets the value of Locale.
func (s *CreateUserRequest) SetLocale(val OptString) {
	s.Locale = val
}

// Ref: #/components/schemas/CreateUserResponse
type CreateUserResponse struct {
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *CreateUserResponse) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *CreateUserResponse) SetID(val uuid.UUID) {
	s.ID = val
}

func (*CreateUserResponse) createUserRes() {}

type CreateUserUnauthorized ErrorResponse

func (*CreateUserUnauthorized) createUserRes() {}

// DeleteMeNoContent is response for DeleteMe operation.
type DeleteMeNoContent struct{}

func (*DeleteMeNoContent) deleteMeRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Code  OptString `json:"code"`
	Error string    `json:"error"`
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() OptString {
	return s.Code
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val OptString) {
	s.Code = val
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

func (*ErrorResponse) deleteMeRes() {}
func (*ErrorResponse) getMeRes()    {}

type GetUserByIdNotFound ErrorResponse

func (*GetUserByIdNotFound) getUserByIdRes() {}

type GetUserByIdUnauthorized ErrorResponse

func (*GetUserByIdUnauthorized) getUserByIdRes() {}

type GetUserByUsernameNotFound ErrorResponse

func (*GetUserByUsernameNotFound) getUserByUsernameRes() {}

type GetUserByUsernameUnauthorized ErrorResponse

func (*GetUserByUsernameUnauthorized) getUserByUsernameRes() {}

// InternalErrorStatusCode wraps ErrorResponse with StatusCode.
type InternalErrorStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *InternalErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *InternalErrorStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *InternalErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// NewOptResourceConflictErrorCode returns new OptResourceConflictErrorCode with value set to v.
func NewOptResourceConflictErrorCode(v ResourceConflictErrorCode) OptResourceConflictErrorCode {
	return OptResourceConflictErrorCode{
		Value: v,
		Set:   true,
	}
}

// OptResourceConflictErrorCode is optional ResourceConflictErrorCode.
type OptResourceConflictErrorCode struct {
	Value ResourceConflictErrorCode
	Set   bool
}

// IsSet returns true if OptResourceConflictErrorCode was set.
func (o OptResourceConflictErrorCode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptResourceConflictErrorCode) Reset() {
	var v ResourceConflictErrorCode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptResourceConflictErrorCode) SetTo(v ResourceConflictErrorCode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptResourceConflictErrorCode) Get() (v ResourceConflictErrorCode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptResourceConflictErrorCode) Or(d ResourceConflictErrorCode) ResourceConflictErrorCode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Merged schema.
// Ref: #/components/schemas/ResourceConflictError
type ResourceConflictError struct {
	// Merged property.
	Code  OptResourceConflictErrorCode `json:"code"`
	Error string                       `json:"error"`
}

// GetCode returns the value of Code.
func (s *ResourceConflictError) GetCode() OptResourceConflictErrorCode {
	return s.Code
}

// GetError returns the value of Error.
func (s *ResourceConflictError) GetError() string {
	return s.Error
}

// SetCode sets the value of Code.
func (s *ResourceConflictError) SetCode(val OptResourceConflictErrorCode) {
	s.Code = val
}

// SetError sets the value of Error.
func (s *ResourceConflictError) SetError(val string) {
	s.Error = val
}

func (*ResourceConflictError) createUserRes() {}
func (*ResourceConflictError) updateMeRes()   {}

// Merged schema.
type ResourceConflictErrorCode string

const (
	ResourceConflictErrorCodeResourceExists ResourceConflictErrorCode = "resource_exists"
)

// AllValues returns all ResourceConflictErrorCode values.
func (ResourceConflictErrorCode) AllValues() []ResourceConflictErrorCode {
	return []ResourceConflictErrorCode{
		ResourceConflictErrorCodeResourceExists,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResourceConflictErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ResourceConflictErrorCodeResourceExists:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResourceConflictErrorCode) UnmarshalText(data []byte) error {
	switch ResourceConflictErrorCode(data) {
	case ResourceConflictErrorCodeResourceExists:
		*s = ResourceConflictErrorCodeResourceExists
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type SessionAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *SessionAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *SessionAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *SessionAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *SessionAuth) SetRoles(val []string) {
	s.Roles = val
}

type TmbAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *TmbAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *TmbAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *TmbAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *TmbAuth) SetRoles(val []string) {
	s.Roles = val
}

type UpdateMeBadRequest ErrorResponse

func (*UpdateMeBadRequest) updateMeRes() {}

// UpdateMeNoContent is response for UpdateMe operation.
type UpdateMeNoContent struct{}

func (*UpdateMeNoContent) updateMeRes() {}

type UpdateMeUnauthorized ErrorResponse

func (*UpdateMeUnauthorized) updateMeRes() {}

type UpdateMyPasswordBadRequest ErrorResponse

func (*UpdateMyPasswordBadRequest) updateMyPasswordRes() {}

// UpdateMyPasswordNoContent is response for UpdateMyPassword operation.
type UpdateMyPasswordNoContent struct{}

func (*UpdateMyPasswordNoContent) updateMyPasswordRes() {}

type UpdateMyPasswordUnauthorized ErrorResponse

func (*UpdateMyPasswordUnauthorized) updateMyPasswordRes() {}

// Ref: #/components/schemas/UpdatePasswordRequest
type UpdatePasswordRequest struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

// GetOldPassword returns the value of OldPassword.
func (s *UpdatePasswordRequest) GetOldPassword() string {
	return s.OldPassword
}

// GetNewPassword returns the value of NewPassword.
func (s *UpdatePasswordRequest) GetNewPassword() string {
	return s.NewPassword
}

// SetOldPassword sets the value of OldPassword.
func (s *UpdatePasswordRequest) SetOldPassword(val string) {
	s.OldPassword = val
}

// SetNewPassword sets the value of NewPassword.
func (s *UpdatePasswordRequest) SetNewPassword(val string) {
	s.NewPassword = val
}

// At least one field must be provided.
// Ref: #/components/schemas/UpdateUserRequest
type UpdateUserRequest struct {
	Username OptString `json:"username"`
	// BCP 47 language tag.
	Locale OptString `json:"locale"`
}

// GetUsername returns the value of Username.
func (s *UpdateUserRequest) GetUsername() OptString {
	return s.Username
}

// GetLocale returns the value of Locale.
func (s *UpdateUserRequest) GetLocale() OptString {
	return s.Locale
}

// SetUsername sets the value of Username.
func (s *UpdateUserRequest) SetUsername(val OptString) {
	s.Username = val
}

// SetLocale sets the value of Locale.
func (s *UpdateUserRequest) SetLocale(val OptString) {
	s.Locale = val
}

// Safe user projection. Never includes the password hash.
// Ref: #/components/schemas/User
type User struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	// BCP 47 language tag.
	Locale string `json:"locale"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *User) GetUsername() string {
	return s.Username
}

// GetLocale returns the value of Locale.
func (s *User) GetLocale() string {
	return s.Locale
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *User) SetUsername(val string) {
	s.Username = val
}

// SetLocale sets the value of Locale.
func (s *User) SetLocale(val string) {
	s.Locale = val
}

func (*User) getMeRes()             {}
func (*User) getUserByIdRes()       {}
func (*User) getUserByUsernameRes() {}
