// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateClient implements createClient operation.
//
// Creates a new OIDC client.
// - `id`: chosen by the caller; must be unique
// - `secret`: plaintext secret — generated if omitted; returned **only once**, store securely
// - `redirect_uris`: at least one URI is required.
//
// POST /clients
func (UnimplementedHandler) CreateClient(ctx context.Context, req *CreateClientRequest) (r CreateClientRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// Creates a new user account.
// - `username`: 3–32 characters, letters/digits/underscores only
// - `password`: minimum 8 characters; stored as a bcrypt hash, never returned
// - `locale`: BCP 47 language tag; defaults to `en` if omitted.
//
// POST /users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserRequest) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteClient implements deleteClient operation.
//
// Delete an OIDC client.
//
// DELETE /clients/{clientId}
func (UnimplementedHandler) DeleteClient(ctx context.Context, params DeleteClientParams) (r DeleteClientRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMe implements deleteMe operation.
//
// Delete the authenticated user.
//
// DELETE /me
func (UnimplementedHandler) DeleteMe(ctx context.Context) (r DeleteMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetClientById implements getClientById operation.
//
// Get an OIDC client by ID.
//
// GET /clients/{clientId}
func (UnimplementedHandler) GetClientById(ctx context.Context, params GetClientByIdParams) (r GetClientByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMe implements getMe operation.
//
// Get the authenticated user.
//
// GET /me
func (UnimplementedHandler) GetMe(ctx context.Context) (r GetMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserByUsername implements getUserByUsername operation.
//
// Get a user by username.
//
// GET /users/by-username/{username}
func (UnimplementedHandler) GetUserByUsername(ctx context.Context, params GetUserByUsernameParams) (r GetUserByUsernameRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMe implements updateMe operation.
//
// Update the authenticated user's username and/or locale.
//
// PATCH /me
func (UnimplementedHandler) UpdateMe(ctx context.Context, req *UpdateUserRequest) (r UpdateMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMyPassword implements updateMyPassword operation.
//
// Verifies `old_password` against the stored bcrypt hash before applying the change.
// Returns `401` for both wrong `old_password` and missing authentication,
// using the same error to prevent information leakage.
//
// PATCH /me/password
func (UnimplementedHandler) UpdateMyPassword(ctx context.Context, req *UpdatePasswordRequest) (r UpdateMyPasswordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *InternalErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *InternalErrorStatusCode) {
	r = new(InternalErrorStatusCode)
	return r
}
