// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAdminKeyAuth handles adminKeyAuth security.
	// Static admin API key configured via the `ADMIN_API_KEY` environment variable.
	// Required for all client management endpoints.
	HandleAdminKeyAuth(ctx context.Context, operationName OperationName, t AdminKeyAuth) (context.Context, error)
	// HandleSessionAuth handles sessionAuth security.
	// Session key issued by the login endpoint.
	// Format: `Bearer <session-key>`.
	HandleSessionAuth(ctx context.Context, operationName OperationName, t SessionAuth) (context.Context, error)
	// HandleTmbAuth handles tmbAuth security.
	// Trust Me Bro — development/internal use only.
	// Format: `Bearer TMB <user-uuid>`.
	HandleTmbAuth(ctx context.Context, operationName OperationName, t TmbAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesAdminKeyAuth is a private map storing roles per operation.
var operationRolesAdminKeyAuth = map[string][]string{
	CreateClientOperation:  []string{},
	DeleteClientOperation:  []string{},
	GetClientByIdOperation: []string{},
}

// GetRolesForAdminKeyAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAdminKeyAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAdminKeyAuth(operation string) []string {
	roles, ok := operationRolesAdminKeyAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesSessionAuth is a private map storing roles per operation.
var operationRolesSessionAuth = map[string][]string{
	CreateUserOperation:        []string{},
	DeleteMeOperation:          []string{},
	GetMeOperation:             []string{},
	GetUserByIdOperation:       []string{},
	GetUserByUsernameOperation: []string{},
	UpdateMeOperation:          []string{},
	UpdateMyPasswordOperation:  []string{},
}

// GetRolesForSessionAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForSessionAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForSessionAuth(operation string) []string {
	roles, ok := operationRolesSessionAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

// operationRolesTmbAuth is a private map storing roles per operation.
var operationRolesTmbAuth = map[string][]string{
	CreateUserOperation:        []string{},
	DeleteMeOperation:          []string{},
	GetMeOperation:             []string{},
	GetUserByIdOperation:       []string{},
	GetUserByUsernameOperation: []string{},
	UpdateMeOperation:          []string{},
	UpdateMyPasswordOperation:  []string{},
}

// GetRolesForTmbAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForTmbAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForTmbAuth(operation string) []string {
	roles, ok := operationRolesTmbAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityAdminKeyAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t AdminKeyAuth
	const parameterName = "X-Admin-Key"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesAdminKeyAuth[operationName]
	rctx, err := s.sec.HandleAdminKeyAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securitySessionAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t SessionAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesSessionAuth[operationName]
	rctx, err := s.sec.HandleSessionAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

func (s *Server) securityTmbAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TmbAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesTmbAuth[operationName]
	rctx, err := s.sec.HandleTmbAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AdminKeyAuth provides adminKeyAuth security value.
	// Static admin API key configured via the `ADMIN_API_KEY` environment variable.
	// Required for all client management endpoints.
	AdminKeyAuth(ctx context.Context, operationName OperationName) (AdminKeyAuth, error)
	// SessionAuth provides sessionAuth security value.
	// Session key issued by the login endpoint.
	// Format: `Bearer <session-key>`.
	SessionAuth(ctx context.Context, operationName OperationName) (SessionAuth, error)
	// TmbAuth provides tmbAuth security value.
	// Trust Me Bro — development/internal use only.
	// Format: `Bearer TMB <user-uuid>`.
	TmbAuth(ctx context.Context, operationName OperationName) (TmbAuth, error)
}

func (s *Client) securityAdminKeyAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.AdminKeyAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"AdminKeyAuth\"")
	}
	req.Header.Set("X-Admin-Key", t.APIKey)
	return nil
}
func (s *Client) securitySessionAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.SessionAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"SessionAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityTmbAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TmbAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TmbAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
