// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateUserOperation        OperationName = "CreateUser"
	DeleteMeOperation          OperationName = "DeleteMe"
	GetMeOperation             OperationName = "GetMe"
	GetUserByIdOperation       OperationName = "GetUserById"
	GetUserByUsernameOperation OperationName = "GetUserByUsername"
	UpdateMeOperation          OperationName = "UpdateMe"
	UpdateMyPasswordOperation  OperationName = "UpdateMyPassword"
)
