// Code generated by ogen, DO NOT EDIT.
package api

type CreateUserRes interface {
	createUserRes()
}

type DeleteMeRes interface {
	deleteMeRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}

type GetUserByUsernameRes interface {
	getUserByUsernameRes()
}

type UpdateMeRes interface {
	updateMeRes()
}

type UpdateMyPasswordRes interface {
	updateMyPasswordRes()
}
