// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreateClientRequest) setDefaults() {
	{
		val := string("client_secret_basic")
		s.TokenEndpointAuthMethod.SetTo(val)
	}
}
