// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateUser implements createUser operation.
	//
	// Creates a new user account.
	// - `username`: 3–32 characters, letters/digits/underscores only
	// - `password`: minimum 8 characters; stored as a bcrypt hash, never returned
	// - `locale`: BCP 47 language tag; defaults to `en` if omitted.
	//
	// POST /users
	CreateUser(ctx context.Context, req *CreateUserRequest) (CreateUserRes, error)
	// DeleteMe implements deleteMe operation.
	//
	// Delete the authenticated user.
	//
	// DELETE /me
	DeleteMe(ctx context.Context) (DeleteMeRes, error)
	// GetMe implements getMe operation.
	//
	// Get the authenticated user.
	//
	// GET /me
	GetMe(ctx context.Context) (GetMeRes, error)
	// GetUserById implements getUserById operation.
	//
	// Get a user by ID.
	//
	// GET /users/{userId}
	GetUserById(ctx context.Context, params GetUserByIdParams) (GetUserByIdRes, error)
	// GetUserByUsername implements getUserByUsername operation.
	//
	// Get a user by username.
	//
	// GET /users/by-username/{username}
	GetUserByUsername(ctx context.Context, params GetUserByUsernameParams) (GetUserByUsernameRes, error)
	// UpdateMe implements updateMe operation.
	//
	// Update the authenticated user's username and/or locale.
	//
	// PATCH /me
	UpdateMe(ctx context.Context, req *UpdateUserRequest) (UpdateMeRes, error)
	// UpdateMyPassword implements updateMyPassword operation.
	//
	// Verifies `old_password` against the stored bcrypt hash before applying the change.
	// Returns `401` for both wrong `old_password` and missing authentication,
	// using the same error to prevent information leakage.
	//
	// PATCH /me/password
	UpdateMyPassword(ctx context.Context, req *UpdatePasswordRequest) (UpdateMyPasswordRes, error)
	// NewError creates *InternalErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *InternalErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
