// Code generated by ogen, DO NOT EDIT.
package api

type CreateClientRes interface {
	createClientRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteClientRes interface {
	deleteClientRes()
}

type DeleteMeRes interface {
	deleteMeRes()
}

type GetClientByIdRes interface {
	getClientByIdRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}

type GetUserByUsernameRes interface {
	getUserByUsernameRes()
}

type UpdateMeRes interface {
	updateMeRes()
}

type UpdateMyPasswordRes interface {
	updateMyPasswordRes()
}
