// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *InternalErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type AdminKeyAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *AdminKeyAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *AdminKeyAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *AdminKeyAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *AdminKeyAuth) SetRoles(val []string) {
	s.Roles = val
}

type CreateClientBadRequest ErrorResponse

func (*CreateClientBadRequest) createClientRes() {}

// Ref: #/components/schemas/CreateClientRequest
type CreateClientRequest struct {
	ID string `json:"id"`
	// Plaintext secret. Generated if omitted.
	Secret                  OptString `json:"secret"`
	RedirectUris            []url.URL `json:"redirect_uris"`
	GrantTypes              []string  `json:"grant_types"`
	ResponseTypes           []string  `json:"response_types"`
	Scope                   OptString `json:"scope"`
	TokenEndpointAuthMethod OptString `json:"token_endpoint_auth_method"`
}

// GetID returns the value of ID.
func (s *CreateClientRequest) GetID() string {
	return s.ID
}

// GetSecret returns the value of Secret.
func (s *CreateClientRequest) GetSecret() OptString {
	return s.Secret
}

// GetRedirectUris returns the value of RedirectUris.
func (s *CreateClientRequest) GetRedirectUris() []url.URL {
	return s.RedirectUris
}

// GetGrantTypes returns the value of GrantTypes.
func (s *CreateClientRequest) GetGrantTypes() []string {
	return s.GrantTypes
}

// GetResponseTypes returns the value of ResponseTypes.
func (s *CreateClientRequest) GetResponseTypes() []string {
	return s.ResponseTypes
}

// GetScope returns the value of Scope.
func (s *CreateClientRequest) GetScope() OptString {
	return s.Scope
}

// GetTokenEndpointAuthMethod returns the value of TokenEndpointAuthMethod.
func (s *CreateClientRequest) GetTokenEndpointAuthMethod() OptString {
	return s.TokenEndpointAuthMethod
}

// SetID sets the value of ID.
func (s *CreateClientRequest) SetID(val string) {
	s.ID = val
}

// SetSecret sets the value of Secret.
func (s *CreateClientRequest) SetSecret(val OptString) {
	s.Secret = val
}

// SetRedirectUris sets the value of RedirectUris.
func (s *CreateClientRequest) SetRedirectUris(val []url.URL) {
	s.RedirectUris = val
}

// SetGrantTypes sets the value of GrantTypes.
func (s *CreateClientRequest) SetGrantTypes(val []string) {
	s.GrantTypes = val
}

// SetResponseTypes sets the value of ResponseTypes.
func (s *CreateClientRequest) SetResponseTypes(val []string) {
	s.ResponseTypes = val
}

// SetScope sets the value of Scope.
func (s *CreateClientRequest) SetScope(val OptString) {
	s.Scope = val
}

// SetTokenEndpointAuthMethod sets the value of TokenEndpointAuthMethod.
func (s *CreateClientRequest) SetTokenEndpointAuthMethod(val OptString) {
	s.TokenEndpointAuthMethod = val
}

// Ref: #/components/schemas/CreateClientResponse
type CreateClientResponse struct {
	ID string `json:"id"`
	// Plaintext client secret — returned only once, store securely.
	Secret string `json:"secret"`
}

// GetID returns the value of ID.
func (s *CreateClientResponse) GetID() string {
	return s.ID
}

// GetSecret returns the value of Secret.
func (s *CreateClientResponse) GetSecret() string {
	return s.Secret
}

// SetID sets the value of ID.
func (s *CreateClientResponse) SetID(val string) {
	s.ID = val
}

// SetSecret sets the value of Secret.
func (s *CreateClientResponse) SetSecret(val string) {
	s.Secret = val
}

func (*CreateClientResponse) createClientRes() {}

type CreateClientUnauthorized ErrorResponse

func (*CreateClientUnauthorized) createClientRes() {}

type CreateUserBadRequest ErrorResponse

func (*CreateUserBadRequest) createUserRes() {}

// Ref: #/components/schemas/CreateUserRequest
type CreateUserRequest struct {
	Username string `json:"username"`
	// Plain text; stored as bcrypt hash, never returned.
	Password string `json:"password"`
	// BCP 47 language tag. Defaults to `en` if omitted.
	Locale OptString `json:"locale"`
}

// GetUsername returns the value of Username.
func (s *CreateUserRequest) GetUsername() string {
	return s.Username
}

// GetPassword returns the value of Password.
func (s *CreateUserRequest) GetPassword() string {
	return s.Password
}

// GetLocale returns the value of Locale.
func (s *CreateUserRequest) GetLocale() OptString {
	return s.Locale
}

// SetUsername sets the value of Username.
func (s *CreateUserRequest) SetUsername(val string) {
	s.Username = val
}

// SetPassword sets the value of Password.
func (s *CreateUserRequest) SetPassword(val string) {
	s.Password = val
}

// SetLocale sets the value of Locale.
func (s *CreateUserRequest) SetLocale(val OptString) {
	s.Locale = val
}

// Ref: #/components/schemas/CreateUserResponse
type CreateUserResponse struct {
	ID uuid.UUID `json:"id"`
}

// GetID returns the value of ID.
func (s *CreateUserResponse) GetID() uuid.UUID {
	return s.ID
}

// SetID sets the value of ID.
func (s *CreateUserResponse) SetID(val uuid.UUID) {
	s.ID = val
}

func (*CreateUserResponse) createUserRes() {}

type CreateUserUnauthorized ErrorResponse

func (*CreateUserUnauthorized) createUserRes() {}

// DeleteClientNoContent is response for DeleteClient operation.
type DeleteClientNoContent struct{}

func (*DeleteClientNoContent) deleteClientRes() {}

type DeleteClientNotFound ErrorResponse

func (*DeleteClientNotFound) deleteClientRes() {}

type DeleteClientUnauthorized ErrorResponse

func (*DeleteClientUnauthorized) deleteClientRes() {}

// DeleteMeNoContent is response for DeleteMe operation.
type DeleteMeNoContent struct{}

func (*DeleteMeNoContent) deleteMeRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Code  OptString `json:"code"`
	Error string    `json:"error"`
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() OptString {
	return s.Code
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() string {
	return s.Error
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val OptString) {
	s.Code = val
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val string) {
	s.Error = val
}

func (*ErrorResponse) deleteMeRes() {}
func (*ErrorResponse) getMeRes()    {}

type GetClientByIdNotFound ErrorResponse

func (*GetClientByIdNotFound) getClientByIdRes() {}

type GetClientByIdUnauthorized ErrorResponse

func (*GetClientByIdUnauthorized) getClientByIdRes() {}

type GetUserByUsernameNotFound ErrorResponse

func (*GetUserByUsernameNotFound) getUserByUsernameRes() {}

type GetUserByUsernameUnauthorized ErrorResponse

func (*GetUserByUsernameUnauthorized) getUserByUsernameRes() {}

// InternalErrorStatusCode wraps ErrorResponse with StatusCode.
type InternalErrorStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *InternalErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *InternalErrorStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *InternalErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// OIDC client metadata. Never includes the secret.
// Ref: #/components/schemas/OIDCClient
type OIDCClient struct {
	ID                      string    `json:"id"`
	RedirectUris            []url.URL `json:"redirect_uris"`
	GrantTypes              []string  `json:"grant_types"`
	ResponseTypes           []string  `json:"response_types"`
	Scope                   string    `json:"scope"`
	TokenEndpointAuthMethod string    `json:"token_endpoint_auth_method"`
	// Unix timestamp.
	CreatedAt int64 `json:"created_at"`
	// Unix timestamp; 0 means no expiry.
	ExpiresAt int64 `json:"expires_at"`
}

// GetID returns the value of ID.
func (s *OIDCClient) GetID() string {
	return s.ID
}

// GetRedirectUris returns the value of RedirectUris.
func (s *OIDCClient) GetRedirectUris() []url.URL {
	return s.RedirectUris
}

// GetGrantTypes returns the value of GrantTypes.
func (s *OIDCClient) GetGrantTypes() []string {
	return s.GrantTypes
}

// GetResponseTypes returns the value of ResponseTypes.
func (s *OIDCClient) GetResponseTypes() []string {
	return s.ResponseTypes
}

// GetScope returns the value of Scope.
func (s *OIDCClient) GetScope() string {
	return s.Scope
}

// GetTokenEndpointAuthMethod returns the value of TokenEndpointAuthMethod.
func (s *OIDCClient) GetTokenEndpointAuthMethod() string {
	return s.TokenEndpointAuthMethod
}

// GetCreatedAt returns the value of CreatedAt.
func (s *OIDCClient) GetCreatedAt() int64 {
	return s.CreatedAt
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *OIDCClient) GetExpiresAt() int64 {
	return s.ExpiresAt
}

// SetID sets the value of ID.
func (s *OIDCClient) SetID(val string) {
	s.ID = val
}

// SetRedirectUris sets the value of RedirectUris.
func (s *OIDCClient) SetRedirectUris(val []url.URL) {
	s.RedirectUris = val
}

// SetGrantTypes sets the value of GrantTypes.
func (s *OIDCClient) SetGrantTypes(val []string) {
	s.GrantTypes = val
}

// SetResponseTypes sets the value of ResponseTypes.
func (s *OIDCClient) SetResponseTypes(val []string) {
	s.ResponseTypes = val
}

// SetScope sets the value of Scope.
func (s *OIDCClient) SetScope(val string) {
	s.Scope = val
}

// SetTokenEndpointAuthMethod sets the value of TokenEndpointAuthMethod.
func (s *OIDCClient) SetTokenEndpointAuthMethod(val string) {
	s.TokenEndpointAuthMethod = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *OIDCClient) SetCreatedAt(val int64) {
	s.CreatedAt = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *OIDCClient) SetExpiresAt(val int64) {
	s.ExpiresAt = val
}

func (*OIDCClient) getClientByIdRes() {}

// NewOptResourceConflictErrorCode returns new OptResourceConflictErrorCode with value set to v.
func NewOptResourceConflictErrorCode(v ResourceConflictErrorCode) OptResourceConflictErrorCode {
	return OptResourceConflictErrorCode{
		Value: v,
		Set:   true,
	}
}

// OptResourceConflictErrorCode is optional ResourceConflictErrorCode.
type OptResourceConflictErrorCode struct {
	Value ResourceConflictErrorCode
	Set   bool
}

// IsSet returns true if OptResourceConflictErrorCode was set.
func (o OptResourceConflictErrorCode) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptResourceConflictErrorCode) Reset() {
	var v ResourceConflictErrorCode
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptResourceConflictErrorCode) SetTo(v ResourceConflictErrorCode) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptResourceConflictErrorCode) Get() (v ResourceConflictErrorCode, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptResourceConflictErrorCode) Or(d ResourceConflictErrorCode) ResourceConflictErrorCode {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Merged schema.
// Ref: #/components/schemas/ResourceConflictError
type ResourceConflictError struct {
	// Merged property.
	Code  OptResourceConflictErrorCode `json:"code"`
	Error string                       `json:"error"`
}

// GetCode returns the value of Code.
func (s *ResourceConflictError) GetCode() OptResourceConflictErrorCode {
	return s.Code
}

// GetError returns the value of Error.
func (s *ResourceConflictError) GetError() string {
	return s.Error
}

// SetCode sets the value of Code.
func (s *ResourceConflictError) SetCode(val OptResourceConflictErrorCode) {
	s.Code = val
}

// SetError sets the value of Error.
func (s *ResourceConflictError) SetError(val string) {
	s.Error = val
}

func (*ResourceConflictError) createClientRes() {}
func (*ResourceConflictError) createUserRes()   {}
func (*ResourceConflictError) updateMeRes()     {}

// Merged schema.
type ResourceConflictErrorCode string

const (
	ResourceConflictErrorCodeResourceExists ResourceConflictErrorCode = "resource_exists"
)

// AllValues returns all ResourceConflictErrorCode values.
func (ResourceConflictErrorCode) AllValues() []ResourceConflictErrorCode {
	return []ResourceConflictErrorCode{
		ResourceConflictErrorCodeResourceExists,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResourceConflictErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ResourceConflictErrorCodeResourceExists:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResourceConflictErrorCode) UnmarshalText(data []byte) error {
	switch ResourceConflictErrorCode(data) {
	case ResourceConflictErrorCodeResourceExists:
		*s = ResourceConflictErrorCodeResourceExists
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type SessionAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *SessionAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *SessionAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *SessionAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *SessionAuth) SetRoles(val []string) {
	s.Roles = val
}

type TmbAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *TmbAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *TmbAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *TmbAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *TmbAuth) SetRoles(val []string) {
	s.Roles = val
}

type UpdateMeBadRequest ErrorResponse

func (*UpdateMeBadRequest) updateMeRes() {}

// UpdateMeNoContent is response for UpdateMe operation.
type UpdateMeNoContent struct{}

func (*UpdateMeNoContent) updateMeRes() {}

type UpdateMeUnauthorized ErrorResponse

func (*UpdateMeUnauthorized) updateMeRes() {}

type UpdateMyPasswordBadRequest ErrorResponse

func (*UpdateMyPasswordBadRequest) updateMyPasswordRes() {}

// UpdateMyPasswordNoContent is response for UpdateMyPassword operation.
type UpdateMyPasswordNoContent struct{}

func (*UpdateMyPasswordNoContent) updateMyPasswordRes() {}

type UpdateMyPasswordUnauthorized ErrorResponse

func (*UpdateMyPasswordUnauthorized) updateMyPasswordRes() {}

// Ref: #/components/schemas/UpdatePasswordRequest
type UpdatePasswordRequest struct {
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

// GetOldPassword returns the value of OldPassword.
func (s *UpdatePasswordRequest) GetOldPassword() string {
	return s.OldPassword
}

// GetNewPassword returns the value of NewPassword.
func (s *UpdatePasswordRequest) GetNewPassword() string {
	return s.NewPassword
}

// SetOldPassword sets the value of OldPassword.
func (s *UpdatePasswordRequest) SetOldPassword(val string) {
	s.OldPassword = val
}

// SetNewPassword sets the value of NewPassword.
func (s *UpdatePasswordRequest) SetNewPassword(val string) {
	s.NewPassword = val
}

// At least one field must be provided.
// Ref: #/components/schemas/UpdateUserRequest
type UpdateUserRequest struct {
	Username OptString `json:"username"`
	// BCP 47 language tag.
	Locale OptString `json:"locale"`
}

// GetUsername returns the value of Username.
func (s *UpdateUserRequest) GetUsername() OptString {
	return s.Username
}

// GetLocale returns the value of Locale.
func (s *UpdateUserRequest) GetLocale() OptString {
	return s.Locale
}

// SetUsername sets the value of Username.
func (s *UpdateUserRequest) SetUsername(val OptString) {
	s.Username = val
}

// SetLocale sets the value of Locale.
func (s *UpdateUserRequest) SetLocale(val OptString) {
	s.Locale = val
}

// Safe user projection. Never includes the password hash.
// Ref: #/components/schemas/User
type User struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	// BCP 47 language tag.
	Locale string `json:"locale"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetUsername returns the value of Username.
func (s *User) GetUsername() string {
	return s.Username
}

// GetLocale returns the value of Locale.
func (s *User) GetLocale() string {
	return s.Locale
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetUsername sets the value of Username.
func (s *User) SetUsername(val string) {
	s.Username = val
}

// SetLocale sets the value of Locale.
func (s *User) SetLocale(val string) {
	s.Locale = val
}

func (*User) getMeRes()             {}
func (*User) getUserByUsernameRes() {}
