// Package postgres provides PostgreSQL-backed implementations of the
// repository interfaces defined in the app layer.
//
// Each repository wraps a [pkg/db.Queries] instance generated by sqlc and
// translates between the pgx/pgtype wire types and the domain types used
// throughout the application.
//
// # Repositories
//
//   - [UserRepo]   — users (create, look up, update, delete)
//   - [ClientRepo] — OIDC clients; secret and registration token are
//     encrypted at rest with AES-256-GCM before being stored
//   - [GrantRepo]  — OIDC grants; JSON columns (auth details, resources,
//     store) are marshaled/unmarshalled transparently
//
// # Error mapping
//
// All repositories translate low-level database errors into domain errors
// before returning them to callers:
//
//   - [pgx.ErrNoRows] → the domain "not found" sentinel (e.g. [users.ErrNotFound])
//   - PostgreSQL unique-violation (SQLSTATE 23505) → the domain duplicate sentinel
//     (e.g. [users.ErrUsernameTaken])
//
// Any other error is returned unwrapped so the caller can inspect it or
// propagate it up the stack.
package postgres
